models/Ads.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "ads".
 *
 * @property integer $Id
 * @property integer $brand_id
 * @property string $model
 * @property integer $price
 * @property string $engine
 * @property string $enginevol
 * @property string $transmission
 * @property string $condition
 * @property integer $run
 * @property string $rudder
 * @property string $phone
 * @property string $fio
 * @property string $photo
 * @property string $metro
 * @property string $address
 * @property string $region
 * @property string $url
 * @property string $year
 * @property integer $average_price
 * @property integer $phone_find
 * @property integer $region_Id
 * @property string $source
 * @property string $info
 */
class Ads extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ads';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['brand_id', 'price', 'run', 'average_price', 'phone_find', 'region_Id', 'rudder'], 'integer'],
            [['photo', 'info'], 'string'],
            [['year'], 'safe'],
            [['model', 'address'], 'string', 'max' => 100],
            [['engine', 'enginevol', 'fio'], 'string', 'max' => 45],
            [['transmission'], 'string', 'max' => 25],
            [['phone', 'source'], 'string', 'max' => 20],
            [['metro', 'region'], 'string', 'max' => 50],
            [['url'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Id' => 'ID',
            'brand_id' => 'Brand ID',
            'model' => 'Model',
            'price' => 'Price',
            'engine' => 'Engine',
            'enginevol' => 'Enginevol',
            'transmission' => 'Transmission',
            'condition' => 'Condition',
            'run' => 'Run',
            'rudder' => 'Rudder',
            'phone' => 'Phone',
            'fio' => 'Fio',
            'photo' => 'Photo',
            'metro' => 'Metro',
            'address' => 'Address',
            'region' => 'Region',
            'url' => 'Url',
            'year' => 'Year',
            'average_price' => 'Average Price',
            'phone_find' => 'Phone Find',
            'region_Id' => 'Region  ID',
            'source' => 'Source',
            'info' => 'Info',
        ];
    }
    public function getBrand(){
        return $this->hasOne(Brands::className(), ['id' => 'brand_id']);
    }
    public function getBody(){
        return $this->hasOne(Body::className(), ['id' => 'body_id']);
    }
}

views/admin/createuser.php
<?php $this->title="Создание пользователя"; ?>
<p class="title">Создание пользователя</p>
<form action="/admin/createuser" method="post" class="create-user-form">
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Логин (номер телефона)</label>
        <input type="text" name="login" id="login">
        <div class="error" id="login-error"></div>
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Имя</label>
        <input type="text" name="name" id="name">
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Пароль</label>
        <input type="password" name="password" id="password">
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Повторите пароль</label>
        <input type="password" name="repeat-password" id="repeat-password">
        <div class="error" id="password-error"></div>
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Баланс</label>
        <input type="text" name="balance" id="balance">
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Тип</label>
        <select id="admin" name="admin">
            <option value="0">обычный пользователь</option>
            <option value="1">администратор</option>
        </select>
    </div>
    <div class="form-line">
        <label>Комментарий</label>
        <textarea name="description" id="description"></textarea>
    </div>
    <input type="submit" class="registration-button" value="Зарегистрировать"/>
</form>

views/admin/edituser.php
<?php $this->title="Редактирование пользователя"; ?>
<p class="title">Редактирование пользователя</p>
<form action="/admin/edituser" method="post" class="create-user-form">
    <input type="hidden" name="id" id="id" value="<?=$user->id;?>">
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Логин (номер телефона)</label>
        <input type="text" name="login" id="login" value="<?=$user->login;?>">
        <div class="error" id="login-error"></div>
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Имя</label>
        <input type="text" name="name" id="name" value="<?=$user->name;?>">
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Баланс</label>
        <input type="text" name="balance" id="balance" value="<?=$user->balance;?>">
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Тип</label>
        <select id="admin" name="admin">
            <option <?=$user->admin==0?'selected':'';?> value="0">обычный пользователь</option>
            <option <?=$user->admin==1?'selected':'';?> value="1">администратор</option>
        </select>
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Состояние</label>
        <select id="admin" name="admin">
            <option <?=$user->state==0?'selected':'';?> value="0">удален</option>
            <option <?=$user->state==1?'selected':'';?> value="1">активен</option>
        </select>
    </div>
    <div class="form-line">
        <label>Комментарий</label>
        <textarea name="description" id="description"><?=$user->description;?></textarea>
    </div>
    <input type="submit" class="registration-button" value="Сохранить"/>
</form>
<p class="title">Смена пароля</p>
<form action="/admin/changeuserpassword" method="post" class="changepassword-user-form">
    <input type="hidden" name="id" value="<?=$user->id;?>">
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Пароль</label>
        <input type="password" name="password" id="password">
    </div>
    <div class="form-line">
        <img class="indicator" src="/resources/img/okay.png"/>
        <label>Повторите пароль</label>
        <input type="password" name="repeat-password" id="repeat-password">
        <div class="error" id="password-error"></div>
    </div>
    <input type="submit" class="changepassword-button" value="Изменить"/>
</form>

views/admin/index.php
<?php $this->title="Объявления"; ?>
<div class="cars-list">
    <table border="1" frame="void"  rules="rows" bordercolor="white">
        <tbody>
            <tr>
                <th width="30" style="text-align: center">
                    ID
                </th>
                <th width="231">
                    Автомобиль
                </th>
                <th width="200">
                    Пользователь
                </th>
                <th width="305">
                    Ссылки на Auto.ru и Avito.ru
                </th>
                <th width="150" style="text-align: center">
                    Дата добавления
                </th>
                <th width="150" style="text-align: center">
                    Статус
                </th>
            </tr>
            <?php foreach ($list as $task):?>
            <tr class="car_<?=$task->id;?> line status_<?=$task->status;?>">
                <td width="30" style="text-align: center">
                    <?=$task->id;?>
                </td>
                <td width="231">
                    <?=$task->model->brand->name;?>
                    <?=$task->model->name;?>,
                    <?=$task->year;?>
                </td>
                <td width="200">
                    <?php if (!empty($task->proxy) && !empty($task->proxy->user)):?>
                        <?=$task->proxy->user->name;?>, <?=$task->proxy->user->login;?>
                    <?php endif; ?>
                </td>
                <td width="305">
                    <input data-id="<?=$task->id;?>" type="text" placeholder="Auto.ru" class="url_input autoru_url" id="autoru_url" value="<?=$task->autoru_url;?>">
                    <input data-id="<?=$task->id;?>" type="text" placeholder="Avito.ru" class="url_input avitoru_url" id="avitoru_url" value="<?=$task->avitoru_url;?>">
                </td>
                <td width="150" style="text-align: center">
                    <?=(new \DateTime($task->createdate))->format('d.m.Y H:i'); ?>
                </td>
                <td width="150">
                    <select class="status" data-prev="<?=$task->status;?>" data-id="<?=$task->id;?>">
                        <?php foreach ($statuses as $num => $status): ?>
                            <?php if ($num==$task->status): ?>
                                <option selected value="<?=$num;?>"><?=$status['user'];?></option>
                            <?php else: ?>
                                <option value="<?=$num;?>"><?=$status['user'];?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

views/admin/proxy.php
<?php $this->title="Прокси"; ?>
<div class="proxy-list">
    <form action="/admin/createproxy" method="post" class="create-proxy-form">
        <div class="form-line proxy-place">
            <input required placeholder="Сервер" type="text" name="proxy" id="proxy" pattern="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}">
        </div>
        <div class="form-line proxy-http">
            <input required placeholder="HTTP" type="text" name="http_port" id="http-port">
        </div>
        <div class="form-line proxy-socks5">
            <input required placeholder="SOCKS5" type="text" name="socks5_port" id="socks5_port">
        </div>
        <div class="form-line proxy-login">
            <input required placeholder="Логин" type="text" name="login" id="login">
        </div>
        <div class="form-line proxy-password">
            <input required placeholder="Пароль" type="text" name="pass" id="password">
        </div>
        
        
        <input type="submit" class="add-proxy-button" value="добавить"/>
    </form>
    
    <span class="unused-amount">не использовано <?=$unused_amount; ?> прокси</span>
    <table border="1" frame="void"  rules="rows" bordercolor="white">
        <tbody>
            <tr>
                <th width="30" style="text-align: center">
                    ID
                </th>
                <th width="360">
                    Сервер / HTTP / SOCKS5 / Логин / Пароль
                </th>
				<th width="110" style="text-align: center">
                    Телефон
                </th>
                <th width="60" style="text-align: center">
                    Auto.ru
                </th>
				<th width="60" style="text-align: center">
                    Avito.ru
                </th>
				<th width="80" style="text-align: center">
                    User
                </th>
				<th width="110" style="text-align: center">
					Объявление
                </td>
                <th width="120" style="text-align: center">
                    Дата добавления
                </th>
            </tr>
            <?php foreach ($proxy_list as $proxy):?>
            <?php 
                $dt = new \DateTime($proxy->createdate);
                $days = (int)($dt->diff(new \DateTime())->format('%R%a'));
            ?>
            <tr class="line <?php if ($proxy->confirmed_avito==0 && $proxy->confirmed_auto==0):?>
                    unused
                <?php elseif ($proxy->confirmed_avito==1 && $proxy->confirmed_auto==0):?>
                    used-partial
                <?php elseif ($proxy->confirmed_avito==0 && $proxy->confirmed_auto==1):?>
                    used-partial
                <?php elseif ($proxy->status==1): ?>
                    used
                <?php elseif ($proxy->status==0): ?>
                    died
                <?php else: ?>
                    used-bulletin
                <?php endif; ?> <?php if ($days>30): ?>
                     old<?php endif; ?>">
                <td width="30" style="text-align: center">
                <?=$proxy->id;?>
                </td>
                <td width="360">
                <?=$proxy->proxy;?> / <?=$proxy->http_port;?> / <?=$proxy->socks5_port;?> / <?=$proxy->proxy_login;?> / <?=$proxy->proxy_pass;?>
                </td>
                <td width="110" style="text-align: center">
				<?=$proxy->phone;?>
                </td>
				<td width="60" style="text-align: center">
				<?=$proxy->confirmed_auto;?>
                </td>
				<td width="60" style="text-align: center">
				<?=$proxy->confirmed_avito;?>
                </td>
				<td width="80" style="text-align: center">
				<?=$proxy->user_id;?>
                </td>
				<td width="110" style="text-align: center">
				12
                </td>
                <td class="data" width="120" style="text-align: center">
                    <?=(new \DateTime($proxy->createdate))->format('d.m.Y H:i'); ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

views/admin/tasks-menu.php
<?php $this->title = "Задания"; ?>
<ul class="tasks-menu">
    <a href="/admin/tasks?action=add"<?php if (empty($_GET['action']) || $_GET['action']=='add'):?>class="active"<?php endif; ?>>
        <li>
            Добавление (<?=$add_count;?>)
        </li>
    </a>
    <a href="/admin/tasks?action=edit"<?php if (!empty($_GET['action']) && $_GET['action']=='edit'):?>class="active"<?php endif; ?>>
        <li>
            Редактирование (<?=$edit_count;?>)
        </li>
    </a>
    <a href="/admin/tasks?action=delete"<?php if (!empty($_GET['action']) && $_GET['action']=='delete'):?>class="active"<?php endif; ?>>
        <li>
            Удаление (<?=$delete_count;?>)
        </li>
    </a>
</ul>

views/admin/users.php
<?php $this->title="Пользователи"; ?>
<div class="users-list">
    <table border="1" frame="void"  rules="rows" bordercolor="white">
        <tbody>
            <tr>
                <th width="30" style="text-align: center">
                    ID
                </th>
                <th width="200">
                    Имя
                </th>
                <th>
                    Логин
                </th>
                <th>
                    Баланс
                </th>
                <th>
                    Объявлений
                </th>
                <th>
                    Переходов
                </th>
                <th width="150" style="text-align: center">
                    Дата регистрации
                </th>
            </tr>
            <?php foreach ($users_list as $user):?>
            <tr class="line">
                <th width="30" style="text-align: center">
                    <?=$user->id; ?>
                </th>
                <th width="200">
                    <?=$user->name; ?>
                </th>
                <th>
                    <?=$user->login; ?>
                </th>
                <th>
                    <?=number_format($user->balance,0,' ',' ');?>
                </th>
                <th>
                    <?php
                        $cars_amount = \app\models\Cars::find()
                        ->where([
                            'owner' => $user->id
                        ])->count();
                    ?>
                    <?=number_format($cars_amount, 0, ' ' ,' ');?>
                </th>
                <th>
                    <?php
                        $op_amount = \app\models\Operations::find()
                            ->where([
                                'user_id' => $user->id,
                                'type' => 'ads'
                            ])->count();
                        $tomorrow = new \DateTime("now", new \DateTimeZone('Europe/Moscow'));
                        $tomorrow->add(new \DateInterval('P1D')); // Завтрашний день
                        $tomorrow = $tomorrow->format("Y-m-d");
                        
                        $today = new \DateTime("now", new \DateTimeZone('Europe/Moscow'));
                        $today = $today->format("Y-m-d");
                        
                        $op_today_amount = \app\models\Operations::find()
                            ->where([
                                'user_id' => $user->id,
                                'type' => 'ads'
                            ])
                            ->andWhere([
                                '>', 'createdate', $today
                            ])
                            ->andWhere([
                                '<', 'createdate', $tomorrow
                            ])
                            ->count();
                        
                    ?>
                    <?=number_format($op_amount, 0, ' ', ' ');?> (<?=number_format($op_today_amount, 0, ' ', ' ');?>)
                </th>
                <th width="150" style="text-align: center">
                    <?=(new \DateTime($user->createdate))->format('d.m.Y H:i'); ?>
                </th>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>