models/Cars.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cars".
 *
 * @property integer $id
 * @property integer $model_id
 * @property integer $year
 * @property integer $body_type
 * @property integer $engine_type
 * @property string $engine_volume
 * @property integer $engine_power
 * @property integer $transmission_type
 * @property integer $drive_type
 * @property integer $color_id
 * @property integer $rudder
 * @property integer $condition
 * @property integer $run
 * @property integer $ad_type
 * @property integer $status
 * @property integer $price
 * @property string $description
 * @property string $contact
 * @property integer $phone
 * @property integer $owner
 */
class Cars extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cars';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['model_id', 'year', 'engine_type', 'engine_volume', 'engine_power', 'transmission_type', 'drive_type', 'color_id', 'rudder', 'condition', 'run', 'ad_type', 'status', 'price', 'contact', 'phone'], 'required'],
            [['model_id', 'year', 'engine_type', 'engine_power', 'transmission_type', 'drive_type', 'color_id', 'rudder', 'condition', 'run', 'ad_type', 'status', 'price', 'body_id'], 'integer'],
            [['engine_volume'], 'number'],
            [['description', 'contact'], 'string']
        ];
    }
    
    
    
    public function getBody(){
        return $this->hasOne(Body::className(), ['id' => 'body_id']);
    }
    
    public static function getEnginetypes()
    {
        return ['Бензин', 'Дизель', 'Гибрид'];
    }
    
    public static function getTransmissiontypes()
    {
        return [
            [
                'name' => 'Механическая',
                'second_name' => 'Механика',
                'shortname' => 'MT'
            ],
            [
                'name' => 'Автоматическая',
                'second_name' => 'Автомат',
                'shortname' => 'AT'
            ],
            [
                'name' => 'Роботизированная',
                'second_name' => 'Робот',
                'shortname' => 'AMT'
            ],
            [
                'name' => 'Вариатор',
                'second_name' => 'Вариатор',
                'shortname' => 'CVT'
            ]
        ];
    }
    
    public static function getDrivetypes()
    {
        return ['Передний','Задний','Полный'];
    }
    
    public static function getRudders()
    {
        return ['Левый','Правый'];
    }
    
    public static function getConditions()
    {
        return ['не битый','битый'];
    }
    
    public static function getAdtypes()
    {
        return ['обычная','турбо-продажа'];
    }
    
    public static function getStatuses()
    {
        return [
            [
                'user' => 'Активен',
                'admin' => 'Активен',
                'order' => 0
            ],
            [
                'user' => 'Размещение',
                'admin' => 'Размещение',
                'order' => 3
            ],
            [
                'user' => 'Удаление',
                'admin' => 'удаление',
                'order' => 6
            ],
            [
                'user' => 'Редактирование',
                'admin' => 'Редактирование',
                'order' => 4
            ],
            [
                'user' => 'Обновление',
                'admin' => 'Обновлен',
                'order' => 5
            ],
            [
                'user' => 'Завершён',
                'admin' => 'Завершён',
                'order' => 1
            ],
            
            [
                'user' => 'Заблокирован',
                'admin' => 'Заблокирован',
                'order' => 2
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'model_id' => 'Model ID',
            'year' => 'Year',
            'engine_type' => 'Engine Type',
            'engine_volume' => 'Engine Volume',
            'engine_power' => 'Engine Power',
            'transmission_type' => 'Transmission Type',
            'drive_type' => 'Drive Type',
            'color_id' => 'Color ID',
            'rudder' => 'Rudder',
            'condition' => 'Condition',
            'run' => 'Run',
            'ad_type' => 'Ad Type',
            'status' => 'Status',
            'price' => 'Price',
            'description' => 'Description',
            'contact' => 'Contact',
            'phone' => 'Phone',
            'owner' => 'Owner'
        ];
    }
    
    public function getColor(){
        return $this->hasOne(Colors::className(), ['id' => 'color_id']);
    }
  /*  public function getSubway(){
        return $this->hasOne(Subwaystations::className(), ['id' => 'subway_id']);
    }*/
    public function getModel(){
        return $this->hasOne(Models::className(), ['id' => 'model_id']);
    }
    public function getPhoto(){
        return $this->hasOne(Photos::className(), ['car_id' => 'id']);
    }
    public function getPhotos(){
        return $this->hasMany(Photos::className(), ['car_id' => 'id']);
    }
    
    public function getProxy(){
        return $this->hasOne(Proxy::className(), ['id' => 'proxy_id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\Cars;
use app\models\Brands;
use app\models\Colors;
use app\models\Subwaystations;
use app\models\Cities;
use app\models\Photos;
use app\models\Models;
use app\models\Users;
use app\models\Ads;
use app\models\Body;
use app\models\Payment;
use app\models\Operations;
use app\models\Sources;
use app\models\Proxy;
use app\models\Phones;

class SiteController extends GlobalController
{
    public function actionPhpinfo(){
        die();
        phpinfo();
        die();
    }
    
    private function mb_ucfirst($string, $encoding='UTF-8')
    {
        $firstChar = mb_substr($string, 0, 1, $encoding);
        $then = mb_substr($string, 1, mb_strlen($string, $encoding)-1, $encoding);
        return mb_strtoupper($firstChar, $encoding) . $then;
    }
    
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'foreColor'=>0x66534F,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
    public function actionClearsearchfilters()
    {
        SetCookie("filter","");
        header( 'Location: /online', true, 302 );
        exit();
    }
    
    public function actionDeleted()
    {
        if (empty(Yii::$app->session->get('id'))){
            header( 'Location: /', true, 302 );
            exit();
        } else {
            $user = Users::find()
                ->where([
                    'id' => Yii::$app->session->get('id')
                ])->one();
            if (empty($user)/* || strcmp($user->session_key, Yii::$app->session->get('session_key'))!=0*/) {
                header( 'Location: /', true, 302 );
                exit();
            }
        }
        if (!empty(Yii::$app->session->get('admin'))){
            header( 'Location: /admin/tasks', true, 302 );
            exit();
        }
        $this->view->registerCssFile('/resources/css/main.css');
        $this->view->registerCssFile('/resources/css/list.css');
        $this->view->registerJsFile('/resources/js/delete.js',['depends'=>'yii\web\JqueryAsset']);
        
        
        $active = Cars::find()
                ->where([
                    'status' => 0,
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $active;
        $activeCount = $countQuery->count();
       
        $moderation = Cars::find()
                ->where([
                    'status' => [1,2,3,4],
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $moderation;
        $moderationCount = $countQuery->count();
        
        
        $ended = Cars::find()
                ->where([
                    'status' => [5,6],
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $ended;
        $endedCount = $countQuery->count();
        if ($endedCount==0){
            header( 'Location: /active', true, 302 );
            exit();
        }
        $ended_list = $ended->all();
                
        
        
    //    $this->view->registerJsFile('/resources/js/index.js',['depends'=>'yii\web\JqueryAsset']);
    //    $this->view->params['brands'] = Brands::find()->orderBy(['name'=> SORT_ASC])->all();
        $this->view->params['off_format_detection'] = true;
        $this->setActivepage('main');
        return $this->render('deleted', [
            'active_count' => $activeCount,
            'moderation_count' => $moderationCount,
            'ended' => $ended_list,
            'ended_count' => $endedCount,
            'body_types' => Body::getPublicBodys(),
            'engine_types' => Cars::getEnginetypes(),
            'transmission_types' => Cars::getTransmissiontypes(),
            'drive_types' => Cars::getDrivetypes(),
            'statuses' => Cars::getStatuses(),
            'months' => parent::monthsShort()
        ]);
    }
    
    public function actionModeration(){
        if (empty(Yii::$app->session->get('id'))){
            header( 'Location: /', true, 302 );
            exit();
        } else {
            $user = Users::find()
                ->where([
                    'id' => Yii::$app->session->get('id')
                ])->one();
            if (empty($user)/* || strcmp($user->session_key, Yii::$app->session->get('session_key'))!=0*/) {
                header( 'Location: /', true, 302 );
                exit();
            }
        }
        if (!empty(Yii::$app->session->get('admin'))){
            header( 'Location: /admin/tasks', true, 302 );
            exit();
        }
        $this->view->registerCssFile('/resources/css/main.css');
        $this->view->registerCssFile('/resources/css/list.css');
        $this->view->registerJsFile('/resources/js/index.js',['depends'=>'yii\web\JqueryAsset']);
        $active = Cars::find()
                ->where([
                    'status' => 0,
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $active;
        $activeCount = $countQuery->count();
        $active_list = $active->all();
        $moderation = Cars::find()
                ->where([
                    'status' => [1,2,3,4],
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $moderation;
        $moderationCount = $countQuery->count();
        if ($moderationCount==0){
            header( 'Location: /active', true, 302 );
            exit();
        }
        $moderation_list = $moderation->all();
        
        $ended = Cars::find()
                ->where([
                    'status' => [5,6],
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $ended;
        $endedCount = $countQuery->count();
                
        
        
    //    $this->view->registerJsFile('/resources/js/index.js',['depends'=>'yii\web\JqueryAsset']);
    //    $this->view->params['brands'] = Brands::find()->orderBy(['name'=> SORT_ASC])->all();
        $this->view->params['off_format_detection'] = true;
        $this->setActivepage('main');
        return $this->render('moderation', [
            'active_count' => $activeCount,
            'moderation' => $moderation_list,
            'moderation_count' => $moderationCount,
            'ended_count' => $endedCount,
            'body_types' => Body::getPublicBodys(),
            'engine_types' => Cars::getEnginetypes(),
            'transmission_types' => Cars::getTransmissiontypes(),
            'drive_types' => Cars::getDrivetypes(),
            'statuses' => Cars::getStatuses(),
            'months' => parent::monthsShort()
        ]);
    }
    
    public function actionActive(){
        if (empty(Yii::$app->session->get('id'))){
            header( 'Location: /', true, 302 );
            exit();
        } else {
            $user = Users::find()
                ->where([
                    'id' => Yii::$app->session->get('id')
                ])->one();
            if (empty($user)/* || strcmp($user->session_key, Yii::$app->session->get('session_key'))!=0*/) {
                header( 'Location: /', true, 302 );
                exit();
            }
        }
        if (!empty(Yii::$app->session->get('admin'))){
            header( 'Location: /admin/tasks', true, 302 );
            exit();
        }
        $this->view->registerCssFile('/resources/css/main.css');
        $this->view->registerCssFile('/resources/css/list.css');
        $this->view->registerJsFile('/resources/js/index.js',['depends'=>'yii\web\JqueryAsset']);
        
        
        $active = Cars::find()
                ->where([
                    'status' => 0,
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $active;
        $activeCount = $countQuery->count();
        $active_list = $active->all();
        $moderation = Cars::find()
                ->where([
                    'status' => [1,2,3,4],
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $moderation;
        $moderationCount = $countQuery->count();
        $moderation_list = $moderation->all();
        
        $ended = Cars::find()
                ->where([
                    'status' => [5,6],
                    'active' => 1,
                    'owner' => Yii::$app->session->get('id')
                ]);
        $countQuery = clone $ended;
        $endedCount = $countQuery->count();
                
        
        
    //    $this->view->registerJsFile('/resources/js/index.js',['depends'=>'yii\web\JqueryAsset']);
    //    $this->view->params['brands'] = Brands::find()->orderBy(['name'=> SORT_ASC])->all();

views/site/balance.php
<?php $this->title="Баланс"; ?>
    <span class="balance">
        <?=$name;?>, Ваш баланс <span class="balance-value"><?=!empty($this->params['balance'])?number_format($this->params['balance'],0,' ',' '):'0';?></span> рублей!
    </span>
    <span class="balance-info">
        При пополнение баланса на сумму от 5 000 руб. – бонус 10%, 15 000 руб. – бонус 20% от суммы пополнения!<br>
        Пополнение на сумму 5 000 руб. и более осуществляется только переводом на карту клиента Сбербанка.<br>
        Подробнее можно узнать по телефону техподдержки: +79251682285.
    </span>
<div class="qiwi-panel">
    <img class="qiwi-logo" src="/resources/img/vqw.png">
    <div class="sum-place">
        <form action="/qiwiredirect" method="post" target="_blank">
            <span class="label">Сумма</span>
            <input name="sum" type="text" id="sum">
            <span class="currency">руб.</span>
            <span class="helper">мин. 200, макс. 4 999 руб.</span>
            <input type="submit" value="Пополнить" class="send">
        </form>
    </div>
</div>
<span class="info">
     Пополнение происходит автоматически. Статус счета на оплату проверяется каждую минуту!<br>
     В случае возникновения каких-либо проблем, свяжитесь с техподдержкой сайта!
</span>
<div class="requisites">
	<span class="text">Дополнительные реквизиты</span>
	<div class="req">
	<p class="req-text">Карта Сбербанка <font class="req-min">(мин. 1 000 руб.)</font></p>
	<p class="req-number">XXXX XXXX XXXX XXXX</p>
	<img class="req-logo" src="/resources/img/sberbank.png">
	</div>
	<div class="req">
	<p class="req-text">Visa QIWI Wallet <font class="req-min">(мин. 500, макс. 4 999 руб.)</font></p>
	<p class="req-number">+79251682285</p>
	<img class="req-logo" src="/resources/img/qiwi.png">
	</div>
	<div class="req">
	<p class="req-text">Карта Альфа-Банка</p>
	<p class="req-number">XXXX XXXX XXXX XXXX</p>
	<img class="req-logo" src="/resources/img/alfabank.png">
	</div>
	<div class="req">
	<p class="req-text">Яндекс.Деньги <font class="req-min">(мин. 1 000, макс. 4 999 руб.)</font></p>
	<p class="req-number">410011644523482</p>
	<img class="req-logo" src="/resources/img/yandex.png">
	</div>
</div>
<span class="info">
     После совершения перевода, необходимо связаться с техподдержкой сайта!<br>
	 Баланс будет пополнен в течение получаса с момента обращения.
</span>

views/site/check.php
<?php $this->title="Проверка тс"; ?>
<div class="development-panel">
    <img src="/resources/img/graycar.png">
    <div class="title">К сожалению, данный раздел временно недоступен!</div>
    <div class="text">Страница находится в разработке.<br>
    С уважением, администрация AM97.RU!</div>
</div>
<p class="inform_text">Получите информацию об автомобиле: нахождении автомобиля в залоге, наличия ограничений<br>на регистрационные действия транспортного средства, дополнительную информацию о тс.<br>Для проверки необходимо ввести идентификационный номер ТС (VIN) и номер СТС.</p>
<div class="form">
					<p class="podpis_2" style="margin-left:25px;">VIN</p>
					<input placeholder="1234567890ABCDEFG" class="input input_width" disabled="disabled">
					<p class="podpis_2">Номер СТС</p>
					<input placeholder="12АА123456" class="input" disabled="disabled">
					<div class="button_2">
						<p>Проверить</p>
					</div>
				</div>
<p class="dilleri">Данные предоставляются порталами Auto.ru и Gibdd.ru.<br>Проверка нахождения автомобился в залоге банках партнеров Auto.ru: «КРЕДИТ ЕВРОПА БАНК» (ЗАО),<br>«Альфа-Банк» (ОАО), «Русфинанс Банк» (ООО), Банк ПТБ (ООО), «БМВ Банк» (ООО), МЕТКОМБАНК, Локо банк,<br>Плюс Банк (ОАО), “Коммерческий Банк «Банк Расчетов и Сбережений»” (ООО), АКБ «РОССИЙСКИЙ КАПИТАЛ» (ОАО).<br>Сайт носит исключительно информационный характер!</p>

views/site/default_about.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;
/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
    <?php foreach ($sngs as $sng): ?>
        <?php echo $sng->color->create_date; ?>
    <br>Материалы:<br>
        <?php foreach ($sng->getMaterials()->all() as $material): ?>
            <?=$material->name;?><br>
        <?php endforeach; ?>
        <?php /*echo $sng->getColor()->one()->name; */?><br>
    <?php endforeach; ?>
        <?php $form = ActiveForm::begin([
                    'id' => 'review-form',
                ]); ?>
        
                <?= $form->field($review_model, 'good_id')->hiddenInput()->label(false) ?>
                <?= $form->field($review_model, 'user_name') ?>

                <?= $form->field($review_model, 'user_email')->input('email') ?>

                <?= $form->field($review_model, 'review')->passwordInput() ?>

                <?= $form->field($review_model, 'verifyCode')->widget(Captcha::className(), [
        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
    ]) ?>

                <?= Html::submitButton('OK', ['class' => 'btn btn-success btn-block']) ?>

            <?php ActiveForm::end(); ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php $this->title="Мои объявления"; ?>
<script>
    var moderation = <?php if (!empty($_GET['value']) && $_GET['value']=='moderation'): ?>true<?php else: ?>false<?php endif; ?>;
</script>
<div class="add-menu">
    <a href="/add" class="add-button-link" id="add-button-link">
        <div class="button bt_1" id="add">
            <p>Добавить объявление</p>
        </div>
    </a>
    <div class="tab-button tab-active tab-button-active">
        <div class="text">
            <span>
            Активные
            </span>
        </div>
        <div class="amount">
            <?=(int)$active_count; ?>
        </div>
    </div>
    <?php if ($moderation_count>0): ?>
        <div class="tab-button tab-moderation">
            <div class="text">
                <a href="/moderation">
                На модерации
                </a>
            </div>
            <div class="amount">
                <?=$moderation_count; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($ended_count>0): ?>
    <div class="tab-button tab-ended">
            <div class="text">
                <a href="/deleted">
                Завершённые
                </a>
            </div>
            <div class="amount">
                <?=$ended_count; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
<?php if ($active_count>0): ?>
<div class="place active-place">
    <div class="list">
    <?php
    $column_counter = 1;
    foreach ($active as $number => $item): ?>
        <div class="col col-<?=$column_counter; ?>">
            <div class="item" data-id="<?=$item->id;?>">
                <?php
                    $photo = $item->photo;
                    $img = "/resources/img/nophoto.png";
                    if ($photo && file_exists($photo->url))
                        $img = $photo->url;
                    if ($photo && !empty($photo->thumb) && file_exists($photo->thumb))
                        $img = $photo->thumb;
                ?>
                <div class="logo" style="background: url('<?=$img; ?>') no-repeat center; background-size: cover;">
					<a href="/update?id=<?=$item->id;?>"><img data-id="<?=$item->id;?>" class="update" src="/resources/img/update.png"/></a>
                    <a href="/edit?id=<?=$item->id;?>"><img data-id="<?=$item->id;?>" class="edit" src="/resources/img/edit.png"/></a>
                    <img data-id="<?=$item->id;?>" class="delete" src="/resources/img/close.png"/>
                    <?php if (!empty($item->autoru_url)): ?>
                        <a class="autoru_url_a" target="_blank" href="<?=$item->autoru_url;?>">
                            <img class="autoru_url" src="/resources/img/autoru.svg"/>
                        </a>
                    <?php endif; ?>
                    <?php if (!empty($item->avitoru_url)): ?>
                        <a class="avitoru_url_a" target="_blank" href="<?=$item->avitoru_url;?>">
                            <img class="avitoru_url" src="/resources/img/avitoru.svg"/>
                        </a>
                    <?php endif; ?>
                </div>
                <div class="info">
                    <div class="mark-and-model">
                        <?=$item->model->brand->name;?> <?=$item->model->name;?>
                        <div class="fade"></div>
                    </div>
                    <div class="year-run"><?=$item->year;?>, <?=number_format($item->run, 0, '.', ' ');?> км</div>
                    <div class="color-bodytype"><?=$item->body->name?>, <?=$item->color->name;?>
                        <?php
                        $str = $item->body->name;
                        $enc = 'UTF-8';?>
                    </div>
                    <div class="v-box-power">
                        <?=number_format($item->engine_volume, 1, '.', ' ');?> <?=$transmission_types[$item->transmission_type]['shortname'];?> (<?=$item->engine_power;?> л.с.)
                    </div>
                    <div class="eng-type-dr-type">
                        <?=$engine_types[$item->engine_type];?>, <?=mb_strtolower($drive_types[$item->drive_type], $enc);?>
                    </div>
					<div class="price"><font style="font-weight: bold; font-size: 11pt;"><?=number_format($item->price, 0, '.', ' ');?></font> руб.</div>
                    <div class="phone">
                        <?=$item->phone; ?>, <?=$item->contact; ?>
                    </div>
                    <div class="status">
						<?php
                            $createdate = new Datetime($item->createdate);
                            $enddate = clone $createdate;
                            $enddate->add(new DateInterval("P".Yii::$app->params['MAX_BULLETIN_LIFETIME']."D"));
                            $curdate = new Datetime();
                            $ost = $curdate->diff($enddate)->format("%d");
                            $last_char = $ost{strlen($ost)-1}; // Посл. символ
                            $day = "";
                            $left = "Осталось";
                            if (in_array($last_char, ["0","5","6","7","8","9"]))
                                $day = "дней";
                            else if ($last_char=="1"){
                                $day = "день";
                                $left = "Остался";
                            } else if (in_array($last_char, ["2","3","4"]))
                                $day = "дня";
                        ?>
                        <?=$left." ".$ost." ".$day; ?>
                    </div>
                </div>
            </div>
        </div>
    <?php
    $column_counter == 5?$column_counter = 1:$column_counter++;
    endforeach;
    ?> 
    </div>
</div>
<?php else: ?>
<div class="warning-panel">
    <img src="/resources/img/graycar.png">
    <div class="title">К сожалению, у Вас нет активных объявлений!</div>
    <div class="text">Вы можете добавить новое объявление с помощью кнопки выше.<br>
    С уважением, администрация AM97.RU!</div>
</div>
<?php endif; ?>

views/site/modal.php
<div>
    <label>Марка автомобиля</label>
    <div>
        <select id="brand" name="brand">
            <option value="0">выберите марку</option>
            <?php foreach($this->params['brands'] as $brand): ?>
            <option value="<?=$brand->id;?>"><?=$brand->name;?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<div>
    <label>Модель автомобиля</label>
    <div>
        <select id="model" name="model">
        </select>
    </div>
</div>

views/site/moderation.php
<?php $this->title="Объявления на модерации"; ?>
<div class="add-menu">
    <a href="/add" class="add-button-link" id="add-button-link">
        <div class="button bt_1" id="add">
            <p>Добавить объявление</p>
        </div>
    </a>
    <div class="tab-button tab-active">
        <div class="text">
            <a href="/">
            Активные
            </a>
        </div>
        <div class="amount">
            <?=(int)$active_count; ?>
        </div>
    </div>
    <?php if ($moderation_count>0): ?>
        <div class="tab-button tab-moderation tab-button-active">
            <div class="text">
                <span>
                На модерации
                </span>
            </div>
            <div class="amount">
                <?=$moderation_count; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($ended_count>0): ?>
    <div class="tab-button tab-ended">
            <div class="text">
                <a href="/deleted">
                Завершённые
                </a>
            </div>
            <div class="amount">
                <?=$ended_count; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
<?php if (empty($active_count) && empty($moderation_count) && empty($ended_count)):?>
<h1>У Вас пока что нет объявлений! Разместите Ваше первое объявление с помощью кнопки выше.</h1>
<?php endif; ?>
<?php if ($moderation_count>0): ?>
<div class="ended-place">
    <div class="list">
    <?php
    $column_counter = 1;
    foreach ($moderation as $number => $item): ?>
        <div class="col col-<?=$column_counter; ?>">
            <div class="item" data-id="<?=$item->id;?>">
                <?php
                    $photo = $item->photo;
                    $img = "/resources/img/nophoto.png";
                    if ($photo && file_exists($photo->url))
                        $img = $photo->url;
                    if ($photo && !empty($photo->thumb) && file_exists($photo->thumb))
                        $img = $photo->thumb;
                ?>
                <div class="logo" style="background: url('<?=$img; ?>') no-repeat center; background-size: cover;">

                </div>
                <div class="info">
                    <div class="mark-and-model">
                        <?=$item->model->brand->name;?> <?=$item->model->name;?>
                        <div class="fade"></div>
                    </div>
                    <div class="year-run"><?=$item->year;?>, <?=number_format($item->run, 0, '.', ' ');?> км</div>
                    <div class="color-bodytype"><?=$item->body->name?>, <?=$item->color->name;?>
                        <?php
                        $str = $item->body->name;
                        $enc = 'UTF-8';?>
                    </div>
                    <div class="v-box-power">
                        <?=number_format($item->engine_volume, 1, '.', ' ');?> <?=$transmission_types[$item->transmission_type]['shortname'];?> (<?=$item->engine_power;?> л.с.)
                    </div>
                    <div class="eng-type-dr-type">
                        <?=$engine_types[$item->engine_type];?>, <?=mb_strtolower($drive_types[$item->drive_type], $enc);?>
                    </div>
					<div class="price"><font style="font-weight: bold; font-size: 11pt;"><?=number_format($item->price, 0, '.', ' ');?></font> руб.</div>
                    <div class="phone">
                        <?=$item->phone; ?>, <?=$item->contact; ?>
                    </div>
                    <div class="status">
						 <?=$statuses[$item->status]['user'];?>
                    </div>
                </div>
            </div>
        </div>
    <?php
    $column_counter == 5?$column_counter = 1:$column_counter++;
    endforeach;
    ?> 
    </div>
</div>
<?php endif; ?>